build:
  version: "1.2"

accounts:
  message: "Welcome to JainBank accounts related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitharay@gmail.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371