build:
  version: "2.1"

cards:
  message: "Welcome to JainBank cards related prod APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandraharald@gmail.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721