build:
  version: "2.0"

cards:
  message: "Welcome to JainBank cards related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragoslech@gmail.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932


###### To run in the browser at port 9000
#http://localhost:9000/h2-console
#http://localhost:9000/swagger-ui/index.html