build:
  version: "2.2"

cards:
  message: "Welcome to JainBank cards related QA APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherrylpankaj@gmail.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267