build:
  version: "3.1"

loans:
  message: "Welcome to JainBank loans related prod APIs "
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "peliassudhir@gmail.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956