spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: "classpath:/config" # config is the folder_name
          search-locations: "file:///C://Users//nitanssj//IdeaProjects//Microservices//config_files" # We have to add file:/// then file_location; Keep a look at the '/'s

server:
  port: 8071