spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"   # config is the folder_name
#          search-locations: "file:///C://Users//nitanssj//IdeaProjects//Microservices//config_files" # We have to add file:/// then file_location; Keep a look at the '/'s

        # Fetching configuration files via Git
        git:
          uri: https://github.com/nitansshujain/configserver.git
          default-label: master   # default-branch
          timeout: 5
          clone-on-start: true
          force-pull: true

# Adding rabbitmq configuration, refreshing the bus only will refresh all the connected MSs
# Adding the rabbitMQ setup here as well
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

# Refresh the MS when any changes occur (actuator/refresh). Here I'm including all the endpoints
# Added because of the dependency of "spring-cloud-config-monitor, and continuously checking the liveliness and readiness of the MSs through webhook and rabbitmq"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071
encrypt:
  key: "NitansshuJain1504"